@startuml
skinparam BoxPadding 10
skinparam ParticipantPadding 20
hide footbox

box "Logic" #LightBlue
participant ":LogicManager" as LogicManager #White
participant ":AddressBookParser" as AddressBookParser #White
participant ":AddStudentCommandParser" as AddStudentCommandParser #White
participant "a:AddStudentCommand" as AddStudentCommand #White
participant "r:CommandResult" as CommandResult #White
end box

box "Model" #LightGreen
participant ":Model" as Model #White
participant "student:Person" as Person #White
end box

[-> LogicManager : execute("add-s n/John...")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add-s n/John...")
activate AddressBookParser

create AddStudentCommandParser
AddressBookParser -> AddStudentCommandParser
activate AddStudentCommandParser

AddStudentCommandParser --> AddressBookParser
deactivate AddStudentCommandParser

AddressBookParser -> AddStudentCommandParser : parse("n/John...")
activate AddStudentCommandParser

create Person
AddStudentCommandParser -> Person
activate Person
Person --> AddStudentCommandParser : student
deactivate Person

create AddStudentCommand
AddStudentCommandParser -> AddStudentCommand : AddStudentCommand(student)
activate AddStudentCommand

AddStudentCommand --> AddStudentCommandParser : a
deactivate AddStudentCommand

AddStudentCommandParser --> AddressBookParser : a
deactivate AddStudentCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddStudentCommand : execute(model)
activate AddStudentCommand

AddStudentCommand -> Model : hasPerson(student)
activate Model
Model --> AddStudentCommand : false
deactivate Model

AddStudentCommand -> Model : addPerson(student)
activate Model
Model --> AddStudentCommand
deactivate Model

create CommandResult
AddStudentCommand -> CommandResult : CommandResult(successMsg)
activate CommandResult
CommandResult --> AddStudentCommand : r
deactivate CommandResult

AddStudentCommand --> LogicManager : r
deactivate AddStudentCommand

[<-- LogicManager : r
deactivate LogicManager

@enduml
